#!/usr/bin/env bash

DIR=$(dirname $0)

search_up ()
(
        while [[ $PWD != "/" ]]; do
                if [[ -e "$1" ]]; then
                        pwd
                fi
                cd ..
        done
)
TEMPLATE_DIR='TEMPLATE_DIR'

IFS=$'\n'
TEMPLATE_DIRS=($(search_up "$TEMPLATE_DIR"))
unset IFS

# Change every element of array : http://web.archive.org/web/20101114051536/http://codesnippets.joyent.com/posts/show/1826  
# Add TEMPLATE_DIR to every element of array
TEMPLATE_DIRS=(${TEMPLATE_DIRS[@]/%/\/"$TEMPLATE_DIR"})

for filepath in "$@"; do
        PROBLEM_NAME=$(basename "$filepath")

        if [[ -e "${filepath}" ]]; then
                echo "${filepath} already exists. Remove it and try again."
                continue
        fi
        mkdir -p "${filepath}"


        for CURRENT_TEMPLATE_DIR in "${TEMPLATE_DIRS[@]}"; do
                cp -r -n "${CURRENT_TEMPLATE_DIR}/." "${filepath}/"
        done

        # Rename PROBLEM_NAME in file names
        find $PWD -type f -print0 | xargs -0 rename "s/template/main/" 
done
